// Танкодром: every line the player reads, in Russian and English.
// The language follows Telegram (or the browser outside it). {name} marks a value
// filled in by the game; both languages must have the same keys and the same marks
// (strings.test.mjs checks it).
(function (root, factory) {
  const strings = factory();
  if (typeof module === 'object' && module.exports) module.exports = strings;
  else root.TankStrings = strings;
})(typeof self !== 'undefined' ? self : this, () => {
'use strict';

const ru = {
  title: 'ТАНКОДРОМ',
  intro: 'Защити штаб от вражеских танков.<br>Кирпич пробивается, сталь держит.',
  best: 'Рекорд: {n}',
  disabled: 'Игра отключена.',
  back: '← к выбору игр',
  hud_score: 'СЧЁТ',
  hud_lives: 'ЖИЗНИ',
  hud_foes: 'ВРАГИ',
  hud_stage: 'УРОВЕНЬ',
  menu_1p: '1 игрок',
  menu_2p: '2 игрока за одной клавиатурой',
  menu_online: 'Онлайн вдвоём',
  menu_look: 'Внешний вид',
  btn_create: 'Создать комнату',
  btn_join: 'Войти',
  code_placeholder: 'код',
  btn_invite: 'Позвать друга в Telegram',
  btn_back: 'Назад',
  btn_next: 'Дальше',
  btn_exit: 'Выйти',
  btn_menu: 'В меню',
  btn_again: 'Ещё раз',
  btn_rematch: 'Реванш',
  btn_share: 'Поделиться итогом',
  btn_continue: 'Продолжить',
  btn_all_games: '← Все игры',
  back_label: 'Назад',
  pause_title: 'ПАУЗА',
  pause_text: 'Игра остановлена.',
  pause_online: 'Онлайн-игра не останавливается: друг играет дальше.',
  link_copied: 'Ссылка скопирована',
  hint: 'Крестовина — ехать, A и B — огонь, ТУРБО — очередь.<br>Клавиатура: стрелки или WASD, огонь — пробел/Z, турбо — C.<br>Вдвоём: 1-й WASD + пробел (турбо G), 2-й стрелки + Enter (турбо K).',
  turbo_a: 'ТУРБО<br>A',
  turbo_b: 'ТУРБО<br>B',
  look_title: 'ВНЕШНИЙ ВИД',
  look_done: 'Готово',
  banner_stage: 'УРОВЕНЬ {n} · {map}',
  game_over: 'ИГРА ОКОНЧЕНА',
  stage_clear: 'УРОВЕНЬ {n} ПРОЙДЕН',
  kills: 'Подбито:',
  kinds: 'обычные|быстрые|скорострелы|броневики',
  all_killed: 'Все танки подбиты.',
  base_lost: 'Штаб разрушен.',
  stage_line: 'Уровень: {n}',
  score_line: 'Счёт: {n}',
  best_line: 'Рекорд: {n}',
  wait_friend_next: 'Ждём, когда друг продолжит…',
  online_title: 'ОНЛАЙН ВДВОЁМ',
  online_menu: 'Создайте комнату и отправьте код другу<br>или введите код, который прислал друг.',
  creating: 'Создаём комнату…',
  joining: 'Входим в комнату {code}…',
  code_6: 'Код — это 6 цифр.',
  room: 'КОМНАТА',
  room_n: 'КОМНАТА {code}',
  room_code: 'Код комнаты: {code}<br>Отправьте код другу и ждите, пока он войдёт.',
  in_room: 'Вы в игре! Ждём начала…',
  link_lost_title: 'СВЯЗЬ ПРЕРВАЛАСЬ',
  reconnecting: 'Переподключаемся…',
  peer_lost_title: 'ДРУГ ПОТЕРЯЛ СВЯЗЬ',
  peer_wait: 'Ждём, пока он вернётся…',
  host_away: 'Друг отошёл позвать вас. Ждём его…',
  lost_title: 'СВЯЗЬ ПОТЕРЯНА',
  link_broke: 'Связь с сервером прервалась.',
  rejoin_late: 'Не удалось вернуться в игру: связи не было слишком долго.',
  rejoin_failed: 'Не удалось вернуться в игру: {why}',
  friend_left: 'Друг вышел из игры.',
  rematch_title: 'РЕВАНШ',
  rematch_go: 'Начинаем!',
  rematch_wait: 'Ждём, когда друг нажмёт «Реванш»…',
  rematch_peer: 'Друг хочет реванш!',
  invite_text: 'Сыграем в «Танкодром» вдвоём? Код комнаты: {code}',
  share_solo: 'Танкодром: я дошёл до уровня {n} и набрал {score} очков. Сможешь лучше?',
  share_duo: 'Танкодром: мы вдвоём дошли до уровня {n} и набрали {score} очков. Сыграем?',
  reopen: 'Закройте игру и откройте её заново кнопкой «Играть» внизу чата с ботом @{bot} (не из старых сообщений: адрес сервера меняется при перезапуске бота).',
  no_server_none: 'Игра не знает адрес сервера, поэтому онлайн недоступен.',
  no_server_http: 'Адрес сервера игры не https, а Telegram пускает только https.',
  no_server_down: 'Сервер игры не отвечает: похоже, адрес устарел.',
  no_server_ws: 'Сервер отвечает, но онлайн-соединение не открылось. Попробуйте ещё раз; если не выходит, возможно, сеть блокирует WebSocket (попробуйте Wi-Fi или мобильный интернет).',
  err_not_found: 'Комната не найдена',
  err_full: 'В комнате уже двое',
  err_busy: 'Сервер занят, попробуйте позже',
  err_create: 'Не удалось создать комнату',
  err_tries: 'Слишком много попыток, подождите минуту',
  err_rooms: 'Слишком много комнат, подождите пару минут',
  err_expired: 'Никто не пришёл, комната закрыта',
  // «Внешний вид»
  cat_tank: 'Танк',
  cat_weather: 'Погода',
  cat_enemies: 'Враги',
  cat_walls: 'Стены',
  cat_ground: 'Фон',
  tank_gold: 'Золотой',
  tank_green: 'Зелёный',
  tank_camo: 'Камуфляж',
  tank_desert: 'Пустынный',
  tank_arctic: 'Арктика',
  tank_crimson: 'Багровый',
  tank_cobalt: 'Кобальт',
  tank_emerald: 'Изумруд',
  weather_day: 'День',
  weather_dusk: 'Закат',
  weather_night: 'Ночь',
  weather_rain: 'Дождь',
  weather_snow: 'Снегопад',
  enemies_steel: 'Стальные',
  enemies_rust: 'Ржавые',
  enemies_sand: 'Песчаные',
  enemies_black: 'Чёрные',
  enemies_ghost: 'Призраки',
  walls_brick: 'Кирпич',
  walls_stone: 'Камень',
  walls_crates: 'Ящики',
  walls_concrete: 'Бетон',
  walls_bags: 'Мешки',
  ground_asphalt: 'Асфальт',
  ground_grass: 'Трава',
  ground_sand: 'Песок',
  ground_snowfield: 'Снег',
  ground_space: 'Космос',
  map_0: 'Перекрёсток',
  map_1: 'Река',
  map_2: 'Лёд и сталь',
  map_3: 'Лабиринт',
  map_4: 'Крепость',
};

const en = {
  title: 'TANK FIELD',
  intro: 'Defend the base from enemy tanks.<br>Bricks break, steel holds.',
  best: 'Best: {n}',
  disabled: 'This game is switched off.',
  back: '← back to games',
  hud_score: 'SCORE',
  hud_lives: 'LIVES',
  hud_foes: 'ENEMIES',
  hud_stage: 'STAGE',
  menu_1p: '1 player',
  menu_2p: '2 players, one keyboard',
  menu_online: 'Online for two',
  menu_look: 'Looks',
  btn_create: 'Create a room',
  btn_join: 'Join',
  code_placeholder: 'code',
  btn_invite: 'Invite a friend in Telegram',
  btn_back: 'Back',
  btn_next: 'Next',
  btn_exit: 'Leave',
  btn_menu: 'Menu',
  btn_again: 'Play again',
  btn_rematch: 'Rematch',
  btn_share: 'Share the result',
  btn_continue: 'Continue',
  btn_all_games: '← All games',
  back_label: 'Back',
  pause_title: 'PAUSE',
  pause_text: 'The game is paused.',
  pause_online: 'Online games do not stop: your friend plays on.',
  link_copied: 'Link copied',
  hint: 'D-pad drives, A and B fire, TURBO fires in bursts.<br>Keyboard: arrows or WASD, fire with Space/Z, turbo with C.<br>Two players: 1st WASD + Space (turbo G), 2nd arrows + Enter (turbo K).',
  turbo_a: 'TURBO<br>A',
  turbo_b: 'TURBO<br>B',
  look_title: 'LOOKS',
  look_done: 'Done',
  banner_stage: 'STAGE {n} · {map}',
  game_over: 'GAME OVER',
  stage_clear: 'STAGE {n} CLEAR',
  kills: 'Destroyed:',
  kinds: 'basic|fast|rapid fire|armored',
  all_killed: 'Every tank is down.',
  base_lost: 'The base is destroyed.',
  stage_line: 'Stage: {n}',
  score_line: 'Score: {n}',
  best_line: 'Best: {n}',
  wait_friend_next: 'Waiting for your friend to go on…',
  online_title: 'ONLINE FOR TWO',
  online_menu: 'Create a room and send the code to a friend<br>or enter the code a friend sent you.',
  creating: 'Creating a room…',
  joining: 'Joining room {code}…',
  code_6: 'The code has 6 digits.',
  room: 'ROOM',
  room_n: 'ROOM {code}',
  room_code: 'Room code: {code}<br>Send the code to a friend and wait for them to join.',
  in_room: 'You are in! Waiting for the start…',
  link_lost_title: 'CONNECTION LOST',
  reconnecting: 'Reconnecting…',
  peer_lost_title: 'FRIEND LOST CONNECTION',
  peer_wait: 'Waiting for them to come back…',
  host_away: 'Your friend stepped out to invite you. Waiting for them…',
  lost_title: 'CONNECTION LOST',
  link_broke: 'The connection to the server broke.',
  rejoin_late: 'Could not get back into the game: the connection was gone too long.',
  rejoin_failed: 'Could not get back into the game: {why}',
  friend_left: 'Your friend left the game.',
  rematch_title: 'REMATCH',
  rematch_go: 'Starting!',
  rematch_wait: 'Waiting for your friend to press «Rematch»…',
  rematch_peer: 'Your friend wants a rematch!',
  invite_text: 'Play «Tank Field» with me? Room code: {code}',
  share_solo: 'Tank Field: I reached stage {n} with {score} points. Can you beat it?',
  share_duo: 'Tank Field: the two of us reached stage {n} with {score} points. Want to play?',
  reopen: 'Close the game and open it again with the «Play» button at the bottom of the chat with @{bot} (not from old messages: the server address changes when the bot restarts).',
  no_server_none: 'The game does not know the server address, so online play is unavailable.',
  no_server_http: 'The game server address is not https, and Telegram only allows https.',
  no_server_down: 'The game server does not answer: the address is probably out of date.',
  no_server_ws: 'The server answers, but the online connection did not open. Try again; if it still fails, your network may block WebSocket (try Wi-Fi or mobile data).',
  err_not_found: 'Room not found',
  err_full: 'The room already has two players',
  err_busy: 'The server is busy, try again later',
  err_create: 'Could not create a room',
  err_tries: 'Too many attempts, wait a minute',
  err_rooms: 'Too many rooms, wait a couple of minutes',
  err_expired: 'Nobody came, the room is closed',
  cat_tank: 'Tank',
  cat_weather: 'Weather',
  cat_enemies: 'Enemies',
  cat_walls: 'Walls',
  cat_ground: 'Ground',
  tank_gold: 'Gold',
  tank_green: 'Green',
  tank_camo: 'Camo',
  tank_desert: 'Desert',
  tank_arctic: 'Arctic',
  tank_crimson: 'Crimson',
  tank_cobalt: 'Cobalt',
  tank_emerald: 'Emerald',
  weather_day: 'Day',
  weather_dusk: 'Dusk',
  weather_night: 'Night',
  weather_rain: 'Rain',
  weather_snow: 'Snowfall',
  enemies_steel: 'Steel',
  enemies_rust: 'Rusty',
  enemies_sand: 'Sand',
  enemies_black: 'Black',
  enemies_ghost: 'Ghosts',
  walls_brick: 'Brick',
  walls_stone: 'Stone',
  walls_crates: 'Crates',
  walls_concrete: 'Concrete',
  walls_bags: 'Sandbags',
  ground_asphalt: 'Asphalt',
  ground_grass: 'Grass',
  ground_sand: 'Sand',
  ground_snowfield: 'Snow',
  ground_space: 'Space',
  map_0: 'Crossroads',
  map_1: 'River',
  map_2: 'Ice and steel',
  map_3: 'Maze',
  map_4: 'Fortress',
};

// Russian for Russian and neighbouring Telegram languages, English for everyone else.
function pickLang(code) {
  return /^(ru|uk|be|kk)\b/i.test(code || '') ? 'ru' : 'en';
}

function make(lang) {
  const dict = lang === 'en' ? en : ru;
  return (key, vars) => {
    let text = key in dict ? dict[key] : (key in ru ? ru[key] : key);
    if (vars) text = text.replace(/\{(\w+)\}/g, (m, k) => (k in vars ? String(vars[k]) : m));
    return text;
  };
}

return { ru, en, pickLang, make };
});
