// Бомбодром: every line the player reads, in Russian and English.
// The language follows Telegram (or the browser outside it). {name} marks a value
// filled in by the game; both languages must have the same keys and the same marks
// (strings.test.mjs checks it).
(function (root, factory) {
  const strings = factory();
  if (typeof module === 'object' && module.exports) module.exports = strings;
  else root.BombStrings = strings;
})(typeof self !== 'undefined' ? self : this, () => {
'use strict';

const ru = {
  title: 'БОМБОДРОМ',
  intro: 'Взрывай блоки, найди дверь и уходи на следующий этап.<br>Дверь открывается, когда врагов не осталось.',
  best: 'Рекорд: {n}',
  disabled: 'Игра отключена.',
  back: '← Все игры',
  hud_score: 'СЧЁТ',
  hud_lives: 'ЖИЗНИ',
  hud_time: 'ВРЕМЯ',
  hud_stage: 'ЭТАП',
  hud_wins: 'ПОБЕДЫ',
  menu_1p: '1 игрок',
  menu_online: 'Дуэль онлайн',
  menu_look: '🎨 Внешний вид',
  btn_create: 'Создать комнату',
  btn_join: 'Войти',
  code_placeholder: 'код',
  btn_invite: 'Позвать друга в Telegram',
  btn_back: 'Назад',
  btn_next: 'Дальше',
  btn_exit: 'Выйти',
  btn_menu: 'В меню',
  btn_again: 'Ещё раз',
  btn_rematch: 'Реванш',
  btn_share: 'Поделиться итогом',
  btn_continue: 'Продолжить',
  btn_all_games: '← Все игры',
  back_label: 'Назад',
  pause_title: 'ПАУЗА',
  pause_text: 'Игра остановлена.',
  pause_online: 'Дуэль не останавливается: друг играет дальше.',
  link_copied: 'Ссылка скопирована',
  hint: 'Крестовина — идти, A — бомба, B — взорвать (с пультом).<br>Клавиатура: стрелки или WASD, бомба — пробел/Z, взорвать — X.',
  banner_stage: 'ЭТАП {n}',
  game_over: 'ИГРА ОКОНЧЕНА',
  you_won: 'ВСЕ ЭТАПЫ ПРОЙДЕНЫ!',
  stage_clear: 'ЭТАП {n} ПРОЙДЕН',
  hurry: 'ВРЕМЯ ВЫШЛО!',
  stage_line: 'Этап: {n}',
  score_line: 'Счёт: {n}',
  best_line: 'Рекорд: {n}',
  kills_line: 'Врагов взорвано: {n}',
  item_got: 'Найдено: {item}',
  duel_intro: 'Вы начинаете у левого края, друг — у правого. Кто первым найдёт дверь и выйдет, выигрывает этап. Бомбы ранят обоих.',
  duel_you: 'Вы первым нашли дверь!',
  duel_friend: 'Друг первым нашёл дверь.',
  duel_won: 'Вы победили в дуэли!',
  duel_lost: 'Друг победил в дуэли.',
  duel_wins: 'Этапов выиграно: вы {me}, друг {friend}',
  wait_friend_next: 'Ждём, когда друг продолжит…',
  online_title: 'ДУЭЛЬ ОНЛАЙН',
  online_menu: 'Создайте комнату и отправьте код другу. Или введите код, который прислал друг.',
  creating: 'Создаём комнату…',
  joining: 'Входим в комнату {code}…',
  code_6: 'Код — это 6 цифр.',
  room: 'КОМНАТА',
  room_n: 'КОМНАТА {code}',
  room_code: 'Код комнаты: {code}<br>Отправьте код другу и ждите, пока он войдёт.',
  in_room: 'Вы в игре! Ждём начала…',
  link_lost_title: 'СВЯЗЬ ПРЕРВАЛАСЬ',
  reconnecting: 'Пробуем вернуться в игру…',
  peer_lost_title: 'ДРУГ ПОТЕРЯЛ СВЯЗЬ',
  peer_wait: 'Ждём, пока он вернётся…',
  host_away: 'Друг отошёл позвать вас. Ждём его…',
  lost_title: 'СВЯЗЬ ПОТЕРЯНА',
  link_broke: 'Связь с сервером прервалась.',
  rejoin_late: 'Не удалось вернуться в игру: связи не было слишком долго.',
  rejoin_failed: 'Не удалось вернуться в игру: {why}',
  friend_left: 'Друг вышел из игры.',
  rematch_title: 'РЕВАНШ',
  rematch_go: 'Начинаем!',
  rematch_wait: 'Ждём, когда друг нажмёт «Реванш»…',
  rematch_peer: 'Друг хочет реванш!',
  invite_text: 'Сыграем в «Бомбодром» вдвоём? Код комнаты: {code}',
  share_solo: 'Бомбодром: я дошёл до этапа {n} и набрал {score} очков. Сможешь лучше?',
  share_duo: 'Бомбодром: дуэль {me}:{friend} по этапам. Сыграем?',
  reopen: 'Закройте игру и откройте её заново кнопкой «Играть» внизу чата с ботом @{bot} (не из старых сообщений: адрес сервера меняется при перезапуске бота).',
  no_server_none: 'Игра не знает адрес сервера, поэтому онлайн недоступен.',
  no_server_http: 'Адрес сервера игры не https, а Telegram пускает только https.',
  no_server_down: 'Сервер игры не отвечает: похоже, адрес устарел.',
  no_server_ws: 'Сервер отвечает, но онлайн-соединение не открылось. Попробуйте ещё раз; если не выходит, возможно, сеть блокирует WebSocket (попробуйте Wi-Fi или мобильный интернет).',
  err_not_found: 'Комната не найдена',
  err_full: 'В комнате уже двое',
  err_busy: 'Сервер занят, попробуйте позже',
  err_create: 'Не удалось создать комнату',
  err_tries: 'Слишком много попыток, подождите минуту',
  err_rooms: 'Слишком много комнат, подождите пару минут',
  err_expired: 'Никто не пришёл, комната закрыта',
  // Items under the blocks
  item_bomb: 'ещё одна бомба',
  item_fire: 'огонь дальше',
  item_speed: 'быстрые ноги',
  item_remote: 'пульт: B взрывает бомбу',
  item_wallpass: 'сквозь блоки',
  item_bombpass: 'сквозь бомбы',
  item_flamepass: 'огонь не страшен',
  item_mystery: 'неуязвимость на 10 секунд',
  // «Внешний вид»
  look_title: 'ВНЕШНИЙ ВИД',
  look_done: 'Готово',
  cat_hero: 'Герой',
  cat_blocks: 'Блоки',
  cat_ground: 'Поле',
  hero_white: 'Белый',
  hero_red: 'Красный',
  hero_blue: 'Синий',
  hero_green: 'Зелёный',
  hero_ninja: 'Ниндзя',
  blocks_brick: 'Кирпич',
  blocks_crates: 'Ящики',
  blocks_hedge: 'Кусты',
  blocks_ice: 'Лёд',
  blocks_candy: 'Карамель',
  ground_grass: 'Трава',
  ground_stone: 'Плитка',
  ground_sand: 'Песок',
  ground_snow: 'Снег',
  ground_night: 'Ночь',
};

const en = {
  title: 'BOMB FIELD',
  intro: 'Blow up the blocks, find the door and go on to the next stage.<br>The door opens when no enemies are left.',
  best: 'Best: {n}',
  disabled: 'This game is switched off.',
  back: '← All games',
  hud_score: 'SCORE',
  hud_lives: 'LIVES',
  hud_time: 'TIME',
  hud_stage: 'STAGE',
  hud_wins: 'WINS',
  menu_1p: '1 player',
  menu_online: 'Online duel',
  menu_look: '🎨 Looks',
  btn_create: 'Create a room',
  btn_join: 'Join',
  code_placeholder: 'code',
  btn_invite: 'Invite a friend in Telegram',
  btn_back: 'Back',
  btn_next: 'Next',
  btn_exit: 'Leave',
  btn_menu: 'Menu',
  btn_again: 'Play again',
  btn_rematch: 'Rematch',
  btn_share: 'Share the result',
  btn_continue: 'Continue',
  btn_all_games: '← All games',
  back_label: 'Back',
  pause_title: 'PAUSE',
  pause_text: 'The game is paused.',
  pause_online: 'A duel does not stop: your friend plays on.',
  link_copied: 'Link copied',
  hint: 'D-pad — walk, A — bomb, B — set it off (with the remote).<br>Keyboard: arrows or WASD, bomb — Space/Z, set off — X.',
  banner_stage: 'STAGE {n}',
  game_over: 'GAME OVER',
  you_won: 'ALL STAGES CLEAR!',
  stage_clear: 'STAGE {n} CLEAR',
  hurry: 'TIME IS UP!',
  stage_line: 'Stage: {n}',
  score_line: 'Score: {n}',
  best_line: 'Best: {n}',
  kills_line: 'Enemies blown up: {n}',
  item_got: 'Found: {item}',
  duel_intro: 'You start at the left edge, your friend at the right. The first one out of the door wins the stage. Bombs hurt both.',
  duel_you: 'You found the door first!',
  duel_friend: 'Your friend found the door first.',
  duel_won: 'You won the duel!',
  duel_lost: 'Your friend won the duel.',
  duel_wins: 'Stages won: you {me}, friend {friend}',
  wait_friend_next: 'Waiting for your friend to go on…',
  online_title: 'ONLINE DUEL',
  online_menu: 'Create a room and send the code to a friend. Or enter the code a friend sent you.',
  creating: 'Creating a room…',
  joining: 'Joining room {code}…',
  code_6: 'The code has 6 digits.',
  room: 'ROOM',
  room_n: 'ROOM {code}',
  room_code: 'Room code: {code}<br>Send the code to a friend and wait for them to join.',
  in_room: 'You are in! Waiting for the start…',
  link_lost_title: 'CONNECTION LOST',
  reconnecting: 'Trying to get back into the game…',
  peer_lost_title: 'FRIEND LOST CONNECTION',
  peer_wait: 'Waiting for them to come back…',
  host_away: 'Your friend stepped out to invite you. Waiting for them…',
  lost_title: 'CONNECTION LOST',
  link_broke: 'The connection to the server broke.',
  rejoin_late: 'Could not get back into the game: the connection was gone too long.',
  rejoin_failed: 'Could not get back into the game: {why}',
  friend_left: 'Your friend left the game.',
  rematch_title: 'REMATCH',
  rematch_go: 'Here we go!',
  rematch_wait: 'Waiting for your friend to press «Rematch»…',
  rematch_peer: 'Your friend wants a rematch!',
  invite_text: 'Let\'s play «Bomb Field» together? Room code: {code}',
  share_solo: 'Bomb Field: I reached stage {n} with {score} points. Can you do better?',
  share_duo: 'Bomb Field: our duel ended {me}:{friend} in stages. Want to play?',
  reopen: 'Close the game and open it again with the «Play» button at the bottom of the chat with @{bot} (not from old messages: the server address changes when the bot restarts).',
  no_server_none: 'The game does not know the server address, so online play is off.',
  no_server_http: 'The game server address is not https, and Telegram only allows https.',
  no_server_down: 'The game server does not answer: the address seems to be out of date.',
  no_server_ws: 'The server answers, but the online connection did not open. Try again; if it keeps failing, your network may block WebSocket (try Wi-Fi or mobile data).',
  err_not_found: 'Room not found',
  err_full: 'The room already has two players',
  err_busy: 'The server is busy, try later',
  err_create: 'Could not create a room',
  err_tries: 'Too many tries, wait a minute',
  err_rooms: 'Too many rooms, wait a couple of minutes',
  err_expired: 'Nobody came, the room is closed',
  item_bomb: 'one more bomb',
  item_fire: 'longer fire',
  item_speed: 'fast feet',
  item_remote: 'remote: B sets the bomb off',
  item_wallpass: 'through blocks',
  item_bombpass: 'through bombs',
  item_flamepass: 'fireproof',
  item_mystery: '10 seconds unhurt',
  look_title: 'LOOKS',
  look_done: 'Done',
  cat_hero: 'Hero',
  cat_blocks: 'Blocks',
  cat_ground: 'Field',
  hero_white: 'White',
  hero_red: 'Red',
  hero_blue: 'Blue',
  hero_green: 'Green',
  hero_ninja: 'Ninja',
  blocks_brick: 'Brick',
  blocks_crates: 'Crates',
  blocks_hedge: 'Bushes',
  blocks_ice: 'Ice',
  blocks_candy: 'Candy',
  ground_grass: 'Grass',
  ground_stone: 'Tiles',
  ground_sand: 'Sand',
  ground_snow: 'Snow',
  ground_night: 'Night',
};

// Russian for Russian and neighbouring Telegram languages, English for everyone else.
function pickLang(code) {
  return /^(ru|uk|be|kk)\b/i.test(code || '') ? 'ru' : 'en';
}

function make(lang) {
  const dict = lang === 'en' ? en : ru;
  return (key, vars) => {
    let text = key in dict ? dict[key] : (key in ru ? ru[key] : key);
    if (vars) text = text.replace(/\{(\w+)\}/g, (m, k) => (k in vars ? String(vars[k]) : m));
    return text;
  };
}

return { ru, en, pickLang, make };
});
