// Достижения. check получает итог (уровня или всей игры) и статистику игрока после его учёта.
export const ACHIEVEMENTS = [
  { code: "first_level", icon: "🚩", title: "Первый флаг", text: "Пройти уровень 1-1",
    titleEn: "First flag", textEn: "Clear level 1-1",
    check: (e) => e.type === "level" && e.level === 0 },
  { code: "underground", icon: "⛏️", title: "Диггер", text: "Пройти подземелье 1-2",
    titleEn: "Digger", textEn: "Clear the underground 1-2",
    check: (e) => e.type === "level" && e.level === 1 },
  { code: "treetops", icon: "🌳", title: "Верхолаз", text: "Пройти верхушки деревьев 1-3",
    titleEn: "Treetopper", textEn: "Clear the treetops 1-3",
    check: (e) => e.type === "level" && e.level === 2 },
  { code: "world_clear", icon: "🏰", title: "Хозяин замка", text: "Пройти весь мир 1",
    titleEn: "Castle keeper", textEn: "Clear the whole world 1",
    check: (e) => e.type === "level" && e.level === 3 },
  { code: "boss_fire", icon: "🔥", title: "Огнемёт", text: "Победить жука-босса огнём",
    titleEn: "Flamethrower", textEn: "Beat the beetle boss with fire",
    check: (e) => e.type === "run" && e.bossFire },
  { code: "no_death_level", icon: "🛡️", title: "Без царапины", text: "Пройти уровень, не потеряв жизнь",
    titleEn: "Not a scratch", textEn: "Clear a level without losing a life",
    check: (e) => e.type === "level" && e.deaths === 0 },
  { code: "no_death_world", icon: "👑", title: "Легенда", text: "Пройти все миры, не потеряв ни одной жизни",
    titleEn: "Legend", textEn: "Clear every world without losing a single life",
    check: (e) => e.type === "run" && e.completed && e.deaths === 0 },
  { code: "speedrun", icon: "⚡", title: "Спидраннер", text: "Пройти уровень, когда на таймере осталось 200 и больше",
    titleEn: "Speedrunner", textEn: "Clear a level with 200 or more left on the timer",
    check: (e) => e.type === "level" && e.timeLeft >= 200 },
  { code: "coins_run_50", icon: "💰", title: "Копилка", text: "Собрать 50 золотых за одну игру",
    titleEn: "Piggy bank", textEn: "Collect 50 gold in one game",
    check: (e) => e.type === "run" && e.coins >= 50 },
  { code: "coins_total_500", icon: "🏦", title: "Кладоискатель", text: "Собрать 500 золотых за всё время",
    titleEn: "Treasure hunter", textEn: "Collect 500 gold in all",
    check: (_e, p) => p.total_coins >= 500 },
  { code: "score_50k", icon: "🎯", title: "50 000", text: "Набрать 50 000 очков за одну игру",
    titleEn: "50 000", textEn: "Score 50 000 in one game",
    check: (e) => e.type === "run" && e.score >= 50000 },
  { code: "games_10", icon: "🎮", title: "Завсегдатай", text: "Сыграть 10 игр",
    titleEn: "Regular", textEn: "Play 10 games",
    check: (_e, p) => p.games >= 10 },
];

// titleEn/textEn — для игроков с английским Telegram (страница выбирает сама).
export const publicList = () => ACHIEVEMENTS.map(({ code, icon, title, text, titleEn, textEn }) => ({ code, icon, title, text, titleEn, textEn }));
